<?php
//TODO:
//LISTAR ALL MATERIAIS QUE TEM CADASTRADOS E DO LADO UM CHECK BOX
//NA SEGUDA ETAPA IRA BUSCAR DOS CHECKBOX SELECIOANDOS QUAIS TOMBOS DE CADA MATERIAL TEM EM ESTOQUE
//NA SEGUNDA ETAPA TERA CHECKBOX PARA CADA TOMBO DE TODOS OS MATERIAS PARA LEVAR PRA TERCEIRA ETAPA
//NA TERCEIRA LISTA TODOS OS TOMBOS SELECIONADOS
?>

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Novo Guia - Selecionar material</title>
</head>
<body>
    
</body>
</html>